logging:
  config:logback.xml
server:
  port: 8080
camel:
  springboot:
    name: ServicesRest
management:
  port: 8081
endpoints:
  enabled: false
  health:
    enabled: true
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s
webservice:
  api:
    path: '/camel'
spring:
   main:
     allow-bean-definition-overriding: true